services:
  sortem:
    environment:
      - SOURCE_DIR=../files
      - SORTING_DIR../sorted
    build: .
    volumes:
      - ${SOURCE_DIR}:/source
      - ${SORTING_DIR}:/sorted
    command: python sortem.py